# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RushApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RushApp
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'GoogleSignIn'

  target 'RushAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RushAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
